// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Image struct {
	ID        string     `json:"id"`
	Path      string     `json:"path"`
	Extention string     `json:"extention"`
	Size      int        `json:"size"`
	Ts        *time.Time `json:"ts"`
	Variety   []*Resized `json:"variety"`
}

type Resized struct {
	Path   string `json:"path"`
	Width  int    `json:"width"`
	Height int    `json:"height"`
}

type SizeInput struct {
	Width  int `json:"width"`
	Height int `json:"height"`
}
